# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_edit.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_edit_form(object):
    def setupUi(self, edit_form):
        edit_form.setObjectName("edit_form")
        edit_form.resize(395, 352)
        font = QtGui.QFont()
        font.setPointSize(12)
        edit_form.setFont(font)
        self.edit_buttons = QtWidgets.QDialogButtonBox(edit_form)
        self.edit_buttons.setGeometry(QtCore.QRect(10, 310, 371, 31))
        self.edit_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.edit_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.edit_buttons.setObjectName("edit_buttons")
        self.formLayoutWidget = QtWidgets.QWidget(edit_form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 9, 371, 291))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.edit_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.edit_layout.setContentsMargins(0, 0, 0, 0)
        self.edit_layout.setObjectName("edit_layout")
        self.label_nickname = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_nickname.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_nickname.setObjectName("label_nickname")
        self.edit_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nickname)
        self.lineedit_nickname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineedit_nickname.setObjectName("lineedit_nickname")
        self.edit_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineedit_nickname)
        self.label_username = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_username.setObjectName("label_username")
        self.edit_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_username)
        self.label_hostname = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_hostname.setObjectName("label_hostname")
        self.edit_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_hostname)
        self.label_iteration = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_iteration.setObjectName("label_iteration")
        self.edit_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_iteration)
        self.label_hint = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_hint.setObjectName("label_hint")
        self.edit_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_hint)
        self.label_substring_start = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_substring_start.setObjectName("label_substring_start")
        self.edit_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_substring_start)
        self.spinbox_substring_start = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinbox_substring_start.setObjectName("spinbox_substring_start")
        self.edit_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinbox_substring_start)
        self.spinbox_substring_end = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinbox_substring_end.setProperty("value", 15)
        self.spinbox_substring_end.setObjectName("spinbox_substring_end")
        self.edit_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinbox_substring_end)
        self.label_substring_end = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_substring_end.setObjectName("label_substring_end")
        self.edit_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_substring_end)
        self.label_base = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_base.setObjectName("label_base")
        self.edit_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_base)
        self.combobox_base = QtWidgets.QComboBox(self.formLayoutWidget)
        self.combobox_base.setObjectName("combobox_base")
        self.edit_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.combobox_base)
        self.label_special_char = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_special_char.setObjectName("label_special_char")
        self.edit_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_special_char)
        self.lineedit_username = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineedit_username.setObjectName("lineedit_username")
        self.edit_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineedit_username)
        self.lineedit_hostname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineedit_hostname.setObjectName("lineedit_hostname")
        self.edit_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineedit_hostname)
        self.spinbox_iteration = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinbox_iteration.setMinimum(1)
        self.spinbox_iteration.setMaximum(999999999)
        self.spinbox_iteration.setObjectName("spinbox_iteration")
        self.edit_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinbox_iteration)
        self.lineedit_hint = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineedit_hint.setObjectName("lineedit_hint")
        self.edit_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineedit_hint)
        self.checkbox_special_char = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkbox_special_char.setText("")
        self.checkbox_special_char.setObjectName("checkbox_special_char")
        self.edit_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkbox_special_char)
        self.label_nickname.setBuddy(self.lineedit_nickname)
        self.label_username.setBuddy(self.lineedit_username)
        self.label_hostname.setBuddy(self.lineedit_hostname)
        self.label_iteration.setBuddy(self.spinbox_iteration)
        self.label_hint.setBuddy(self.lineedit_hint)
        self.label_substring_start.setBuddy(self.spinbox_substring_start)
        self.label_substring_end.setBuddy(self.spinbox_substring_end)
        self.label_base.setBuddy(self.combobox_base)
        self.label_special_char.setBuddy(self.checkbox_special_char)

        self.retranslateUi(edit_form)
        self.edit_buttons.accepted.connect(edit_form.accept)
        self.edit_buttons.rejected.connect(edit_form.reject)
        QtCore.QMetaObject.connectSlotsByName(edit_form)
        edit_form.setTabOrder(self.label_nickname, self.lineedit_nickname)
        edit_form.setTabOrder(self.lineedit_nickname, self.lineedit_username)
        edit_form.setTabOrder(self.lineedit_username, self.lineedit_hostname)
        edit_form.setTabOrder(self.lineedit_hostname, self.spinbox_iteration)
        edit_form.setTabOrder(self.spinbox_iteration, self.lineedit_hint)
        edit_form.setTabOrder(self.lineedit_hint, self.spinbox_substring_start)
        edit_form.setTabOrder(self.spinbox_substring_start, self.spinbox_substring_end)
        edit_form.setTabOrder(self.spinbox_substring_end, self.combobox_base)
        edit_form.setTabOrder(self.combobox_base, self.checkbox_special_char)

    def retranslateUi(self, edit_form):
        _translate = QtCore.QCoreApplication.translate
        edit_form.setWindowTitle(_translate("edit_form", "Edit password data"))
        self.label_nickname.setText(_translate("edit_form", "&Nickname:"))
        self.label_username.setText(_translate("edit_form", "&Username:"))
        self.label_hostname.setText(_translate("edit_form", "&Hostname:"))
        self.label_iteration.setText(_translate("edit_form", "&Iteration:"))
        self.label_hint.setText(_translate("edit_form", "&Hint:"))
        self.label_substring_start.setText(_translate("edit_form", "Substring &start:"))
        self.label_substring_end.setText(_translate("edit_form", "Substring &end:"))
        self.label_base.setText(_translate("edit_form", "&Base:"))
        self.label_special_char.setText(_translate("edit_form", "Special &char:"))

