# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_form(object):
    def setupUi(self, main_form):
        main_form.setObjectName("main_form")
        main_form.resize(541, 181)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_form.sizePolicy().hasHeightForWidth())
        main_form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        main_form.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(main_form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 521, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.button_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.button_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.button_layout.setObjectName("button_layout")
        self.button_get = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_get.setObjectName("button_get")
        self.button_layout.addWidget(self.button_get)
        self.button_hint = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_hint.setObjectName("button_hint")
        self.button_layout.addWidget(self.button_hint)
        self.button_new = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_new.setObjectName("button_new")
        self.button_layout.addWidget(self.button_new)
        self.button_update = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_update.setObjectName("button_update")
        self.button_layout.addWidget(self.button_update)
        self.button_delete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_delete.setObjectName("button_delete")
        self.button_layout.addWidget(self.button_delete)
        self.formLayoutWidget = QtWidgets.QWidget(main_form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 521, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.main_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.label_which_password = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_which_password.setTextFormat(QtCore.Qt.AutoText)
        self.label_which_password.setObjectName("label_which_password")
        self.main_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_which_password)
        self.combobox_password_nicknames = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_password_nicknames.sizePolicy().hasHeightForWidth())
        self.combobox_password_nicknames.setSizePolicy(sizePolicy)
        self.combobox_password_nicknames.setObjectName("combobox_password_nicknames")
        self.main_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combobox_password_nicknames)
        self.label_enter_proto = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_enter_proto.setObjectName("label_enter_proto")
        self.main_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_enter_proto)
        self.lineedit_enter_proto = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_enter_proto.sizePolicy().hasHeightForWidth())
        self.lineedit_enter_proto.setSizePolicy(sizePolicy)
        self.lineedit_enter_proto.setObjectName("lineedit_enter_proto")
        self.main_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineedit_enter_proto)
        self.checkbox_show_password = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkbox_show_password.setChecked(True)
        self.checkbox_show_password.setObjectName("checkbox_show_password")
        self.main_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkbox_show_password)
        self.label_resp_header = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resp_header.setFont(font)
        self.label_resp_header.setObjectName("label_resp_header")
        self.main_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_resp_header)
        self.label_resp_body = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resp_body.sizePolicy().hasHeightForWidth())
        self.label_resp_body.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resp_body.setFont(font)
        self.label_resp_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_resp_body.setText("")
        self.label_resp_body.setObjectName("label_resp_body")
        self.main_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_resp_body)
        self.label_which_password.setBuddy(self.combobox_password_nicknames)
        self.label_enter_proto.setBuddy(self.lineedit_enter_proto)

        self.retranslateUi(main_form)
        QtCore.QMetaObject.connectSlotsByName(main_form)

    def retranslateUi(self, main_form):
        _translate = QtCore.QCoreApplication.translate
        main_form.setWindowTitle(_translate("main_form", "KeyMaster - Password Manager"))
        self.button_get.setText(_translate("main_form", "&Get"))
        self.button_hint.setText(_translate("main_form", "&Hint"))
        self.button_new.setText(_translate("main_form", "&New"))
        self.button_update.setText(_translate("main_form", "&Update"))
        self.button_delete.setText(_translate("main_form", "&Delete"))
        self.label_which_password.setText(_translate("main_form", "&Which password? "))
        self.combobox_password_nicknames.setToolTip(_translate("main_form", "Please select a password"))
        self.label_enter_proto.setText(_translate("main_form", "&Enter proto-password: "))
        self.checkbox_show_password.setText(_translate("main_form", "&Show proto-password"))
        self.label_resp_header.setText(_translate("main_form", "Password:"))

